encyclopedia/urls.py
from django.urls import path
from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("add",views.add,name="add"),
    path("random",views.random,name="random"),
    path("<str:title>",views.title,name="title"),
    path("search/",views.search,name="search"),
    path("edit/<str:entry>",views.edit,name="edit"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from contextlib import redirect_stderr
from django.http import HttpResponseRedirect
from django.shortcuts import render,redirect,HttpResponse
from markdown2 import Markdown
from . import util
from django import forms
from django.urls import reverse
from random import choice
class NewPageForm(forms.Form):
    title = forms.CharField(label="Title", required=True, widget= forms.TextInput(attrs={"class":"form-control"}),)
    content = forms.CharField(label="content",required=True,widget = forms.Textarea(attrs = {"class":"form-control"}),)



def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def title(request,title):
    content = util.get_entry(title)
    return render(request, "encyclopedia/page.html", {
        "content": Markdown().convert(content) ,
        "title":title
        })

def edit(request,entry):
    if request.method== "GET":
        title = entry
        content = util.get_entry(title)
        form = NewPageForm({"title":title,"content":content})
        return render(request,"encyclopedia/edit.html",{
            "form":form,
            "title":title
    })
    form = NewPageForm(request.POST)
    if form.is_valid():
        title = form.cleaned_data["title"]
        content = form.cleaned_data["content"]
        util.save_entry(title,content)
        return HttpResponseRedirect(reverse("encyclopedia:title",args=[title]))

def add(request):
    if request.method == "POST":
        form = NewPageForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            util.save_entry(title,content)
            return HttpResponseRedirect(reverse("encyclopedia:index"))
        else:
            return render(request,"encyclopedia/add.html",{
                "form": form
            })
    return render(request,"encyclopedia/add.html",{
        "form": NewPageForm()
    })

# def random(request):
#     entries = util.list_entries()
#     rand_entry = entries[randint(0, len(entries) - 1)]
#     #return redirect("encyclopedia:title",rand_entry)
#     return HttpResponse(rand_entry)
def random(request):
    entries = util.list_entries()
    rand_entry = choice(entries)
    return redirect("encyclopedia:title",rand_entry)

def search(request):
    query = request.GET.get("q")
    entries = util.list_entries()
    if query is None or query == "":
        return render(request,"encyclopedia/index.html")
    else:
        if query in entries:
            return redirect("encyclopedia:title",query)
        found_entries = [
            valid_entries
            for valid_entries in entries
            if query.lower() in valid_entries.lower()
        ]
        return render(request, "encyclopedia/search.html",{
            "query": query,
            "found_entries":found_entries
        })
        


    

encyclopedia/templates/encyclopedia/add.html
{% extends "encyclopedia/layout.html" %}
{% block title %}
Add| Encyclopedia
{% endblock %}
{% block body %}
<h2>Add Page</h2>
<form action="{% url 'encyclopedia:add' %}" method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit">
</form>

{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}
{% block title %}
{{title}}
{% endblock %}
{% block body %}
<h2>Edit</h2>
<form action="{% url 'encyclopedia:edit' title %}" method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit">
</form>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:title' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                   <a href="{% url 'encyclopedia:add' %}"> Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/page.html
{% extends "encyclopedia/layout.html" %}
{% block title %}
{{title}}|  Encyclopedia
{% endblock %}
<h1>Hello WOrld</h1>
{% block body %}
{{content|safe}}
<br><p>Sonething wrong? Click <a href="{% url 'encyclopedia:edit' title %}">here</a> to edit.</p>
{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}
{% block title %}
{{query}}| Encyclopedia
{% endblock %}

{% block body %}
{% if found_entries %}
<br>
<h4>There are matching records</h4>
<ul>
{% for entries in found_entries %}
    <li><a href="{% url 'encyclopedia:title' entries %}">{{ entries }}</a></li>
{% endfor %}
</ul>
{% else %}
<h3>No matching records, please try again</h3>
{% endif %}

{% endblock %}